"""Initial migration.

Revision ID: 4fc23372ebb8
Revises: 
Create Date: 2024-06-13 10:23:04.125689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fc23372ebb8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approval_limit', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('approved_claims_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.drop_column('approved_claims_count')
        batch_op.drop_column('approval_limit')

    # ### end Alembic commands ###
