"""Initial migration.

Revision ID: ca99e4bae36d
Revises: 4fc23372ebb8
Create Date: 2024-06-13 10:59:23.291948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca99e4bae36d'
down_revision = '4fc23372ebb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('intern_organization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('intern_organization', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
